### ISSUE TITLE
read_excel: some errors

### ISSUE THREAD

**Issue by KritiPoudel** [leombastos/2023_AdvPA#10]
While running read_excel code, it does not show "data" if I click on "tab"
I have to manually type "data" on >> soyk <- read_excel ("../data/soybeans.xlsx").
Could I get some suggestions on this?

**Comment by leombastos** [comment]
Hi Kriti. 
Even though it doesn't appear when you hit tab, if you run that line of code, does it import the data (does it appear on your environment)?

If not, then check these:
- Is your RStudio environment set up with the proper project (do you see the project name on the top right corner, or does it say Project (none))?
- In RStudio, bottom right panel, under the `Files` tab, do you see the sub-folders code data output?
- Make sure you set up the folders and subfolders as shown in class
- Make sure you created the RStudio project at the proper folder level (see on video)
- When you run `library("readxl")`, does it load without giving errors?

**Comment by KritiPoudel** [comment]
Probably it is because of the folder and sub-folder setup locations. Other bullets are well-defined in RStudio.

**Comment by leombastos** [comment]
Kriti, were you able to figure it out? 
If not, let me know and we can connect some time before next Monday to go over it.
