### ISSUE TITLE
Error in UseMethod("unite") : 

### ISSUE THREAD

**Issue by saramctabi** [leombastos/2023_AdvPA#14]
Error in UseMethod("unite") : 
  no applicable method for 'unite' applied to an object of class "function"

Does anyone know about this error?

**Comment by leombastos** [comment]
Hi Sara,

Please copy and paste the code that generates this error.
That will help to troubleshoot what may be going on.

Thanks,

Leo.

**Comment by saramctabi** [comment]
Thank you Dr.Bastos,
soyk_u <- unite(location, rep)

**Comment by saramctabi** [comment]
I think I should have put the latest data in the function as well. but anyway, it removes the locations from the resulted column. Should I use merge() instead?

**Comment by thapashekhar** [comment]
Here, unite() function joins location column and rep column into a single column. Are you sure you want to do this?

**Comment by saramctabi** [comment]
Not for the assignment, but for something similar I was trying merge and unite, looking for a function that reverses separate. But, I got the same error for my data as well.

**Comment by thapashekhar** [comment]
I believe you have missed some arguments in the unite() function.

From internet I found this.
unite(data_frame, col, target_columns, sep, remove)

Parameters: 

data_frame: The dataframe to merge its columns.
col: The parameter to determine the name of the new column.
target_columns: The name of columns that are used to merge.
sep: The type of separation that is used for the data of the new columns.
remove: Boolean value. The default value is TRUE. Remove target columns in the new data frame.

**Comment by thapashekhar** [comment]
You have used only target_columns.

**Comment by saramctabi** [comment]
Thank you! I will try it now!
