### ISSUE TITLE
filtering rows in timeseries data

### ISSUE THREAD

**Issue by KritiPoudel** [leombastos/2023_AdvPA#16]
How would we select the time period from 11:00 followed by 11:30, 12:00 until 17:00?

**Comment by leombastos** [comment]
Hi Kriti,

To filter multiple cases, you can use the | operator (think of it as "or").

You could do something like:

`
df %>%
   filter(time == 11:00 |
              time == 11:30 |
              time > 12:00 & time < 17:00)
`

The only thing  to consider is that `time` needs to be of type numerical/double or date.

Good luck!

**Comment by KritiPoudel** [comment]
Thank you, Dr. Bastos!
