### ISSUE TITLE
comparison (>=) is possible only for atomic and list types

### ISSUE THREAD

**Issue by saramctabi** [leombastos/2023_AdvPA#27]
Hi everyone, 
Any ideas how to fix this error? or what does it mean?!

Error in min >= upperT : 
  comparison (>=) is possible only for atomic and list types

Thanks

**Comment by saramctabi** [comment]
<img width="1440" alt="Screen Shot 2023-02-10 at 13 29 34" src="https://user-images.githubusercontent.com/121027393/218169647-78d59782-ddc2-490b-aa6b-a7945d3d49a8.png">

**Comment by saramctabi** [comment]
<img width="1440" alt="Screen Shot 2023-02-10 at 13 32 48" src="https://user-images.githubusercontent.com/121027393/218170325-8b7c4658-78f3-4dba-8724-e70e7c032a2a.png">

**Comment by pngimbwa** [comment]
You may want to rename the min and max object (e.g. renaming max and min to max_temp and mini_temp respectively). Apparently, you are comparing your upperT object with the r min function.

**Comment by leombastos** [comment]
Not the solution to your problem, but I would highly recommend you used `case_when()` (as we did in class) instead of multiple else ifs, for clarity and readability.

**Comment by saramctabi** [comment]
Thank you Dr. Bastos. it works now.
