### ISSUE TITLE
Rendering issue with Mini-Project 

### ISSUE THREAD

**Issue by Trippsmith55** [leombastos/2023_AdvPA#38]
<img width="891" alt="Screen Shot 2023-02-16 at 12 28 25 PM" src="https://user-images.githubusercontent.com/122310926/219442299-11ac4989-cfc2-4629-b856-4dac8da885a3.png">

I am having an issue rendering the Mini-Project.  When I go to render it is giving me this error code. Does anyone know how to fix this?  All my chunks run as well.  Thanks

**Comment by leombastos** [comment]
Tripp, the error says object `peanut` not found.

Go back to lines 64-69 and try to see if you're not invoking `peanut` before creating it, or maybe if it is misspelled.

**Comment by Trippsmith55** [comment]
I have object (peanut) loaded in the environment tab and when I hit run it works.  I am not quite sure what else to do to fix it.  I don't think I am invoking it before creating and it is spelled right.

**Comment by leombastos** [comment]
Try cleaning your environment (by clicking on the brush symbol), and then run each chunk at a time.
That will let you troubleshoot and look for which chunk is causing the issue when you run them individually.
If a chunk doesn't run when you are going one by one, then that is the chunk stopping it from rendering.

Let me know how it goes.

**Comment by Trippsmith55** [comment]
I got it to render.  Thank you!
