### ISSUE TITLE
Animated map

### ISSUE THREAD

**Issue by UM004** [leombastos/2023_AdvPA#39]
Hello everyone,
I am still having the same error as before even after installing the gifski and png packages. I am getting error in the last part of the code.
Anyone else having the same issue?
![Screenshot (316)](https://user-images.githubusercontent.com/122295650/219447056-12eeb0b5-5e1c-4d32-8bf1-43424842edaf.png)
![Screenshot (315)](https://user-images.githubusercontent.com/122295650/219447095-8ffc7996-737a-4bb6-bf3b-61f2c3fae8a8.png)

**Comment by leombastos** [comment]
Check this issue: https://github.com/leombastos/2023_AdvPA/issues/18

**Comment by UM004** [comment]
Professor,
I went through it and installed both the packages i.e. gifski and png then I restarted the R but still the same.
