### ISSUE TITLE
Attendance Apr 3

### ISSUE THREAD

**Issue by leombastos** [leombastos/2023_AdvPA#52]

**Comment by pngimbwa** [comment]
Present

**Comment by alexisherring** [comment]
present

**Comment by AmrinderJakhar98** [comment]
present

**Comment by Leoanish** [comment]
present

**Comment by beau-williams-63** [comment]
present

**Comment by poudelsandesh** [comment]
Present

**Comment by tynerkilgore** [comment]
present

**Comment by dts55213** [comment]
present

**Comment by UM004** [comment]
present

**Comment by austinwinkler** [comment]
PRESENT

**Comment by denis68182** [comment]
present

**Comment by dosterharper** [comment]
Dr. Bastos - I attended class in-person on April 3, but unfortunately I had to leave right at 10am to make it to another meeting so I was not able to claim my attendance in class.  I just finished watching the YouTube recording, though.
