### ISSUE TITLE
Final Project Wrangling Issue

### ISSUE THREAD

**Issue by Trippsmith55** [leombastos/2023_AdvPA#66]
<img width="722" alt="Screen Shot 2023-05-02 at 8 21 51 PM" src="https://user-images.githubusercontent.com/122310926/235812277-a01cb477-b1f1-474e-8bfe-399f37f06443.png">
 
Does anyone know why this is saying that DryYield doesn’t exist?  I see it in the table expressed the same way I typed it.  Thanks

**Comment by saramctabi** [comment]
Try dry_yield instead, you did clean_names() before.

**Comment by Trippsmith55** [comment]
That worked!  Thanks!
