### ISSUE TITLE
problem with yield map

### ISSUE THREAD

**Issue by alexisherring** [leombastos/2023_AdvPA#70]
I know I'm a little behind but I'm having trouble running the following code:
<img width="959" alt="Screen Shot 2023-05-04 at 3 36 06 PM" src="https://user-images.githubusercontent.com/122289145/236311467-b10ffc31-b654-4dc8-ab09-76a21f67eef4.png">

I think part of the issue is that my boundary file has layers, but I'm not sure how to fix that.
<img width="959" alt="Screen Shot 2023-05-04 at 3 44 00 PM" src="https://user-images.githubusercontent.com/122289145/236312912-db4e7ea6-01bc-4267-baf8-2afac2d0f74c.png">

Could anyone help me out with this?

**Comment by saramctabi** [comment]
just use one of those boundary layers, boundary_w[1,] or [2,].

**Comment by alexisherring** [comment]
> 

I can't get that to work either, same error! I've tried [1] and [1,] and [[1]] (pretty much any combo I can think of). If you have any other tips please let me know :)

**Comment by saramctabi** [comment]
The easiest option would be to write boundary_w[1,] wherever you need the boundary. let me know if it worked.

**Comment by thapashekhar** [comment]
@alexisherring, Coud you show the output of yieldmap_corny?

**Comment by alexisherring** [comment]
<img width="959" alt="Screen Shot 2023-05-04 at 7 01 21 PM" src="https://user-images.githubusercontent.com/122289145/236347972-8b60f4fe-15de-4737-a1c4-9987debcec45.png">

**Comment by thapashekhar** [comment]
If you are overlaying boundary and buffer on the field map, I would suggest you to use a map generated from geom_sf() rather than mapview. 
For me in this project, I have not used any maps generated from mapview().

**Comment by thapashekhar** [comment]
solution:  your yieldmap_corny map should be generated using ggplot(), geom_sf() and yield data.

**Comment by alexisherring** [comment]
Okay, will try that! Thank you!

**Comment by alexisherring** [comment]
Sorry y'all I was just making this harder than it needed to be! Thanks for the help
